SET SQLITE_OPTIONS=/D SQLITE_ENABLE_COLUMN_METADATA /D SQLITE_ENABLE_FTS3_PARENTHESIS /D SQLITE_ENABLE_FTS4 /D SQLITE_ENABLE_JSON1 /D SQLITE_ENABLE_RTREE /D SQLITE_DEFAULT_FOREIGN_KEYS=1 /D "SQLITE_API=__declspec(dllexport)" /D SQLITE_WIN32_FILEMAPPING_API=1

echo "TODO figure out if manifest should be embedded.  looks like WP80 can't"

rem SET LIBS=kernel32.lib user32.lib uuid.lib 
rem SET LIBS=WindowsPhoneCore.lib RuntimeObject.lib PhoneAppModelHost.lib 
rem SET MANIFEST_OPTIONS=/MANIFEST /ManifestFile:"obj\Release\e_sqlite3.dll.intermediate.manifest" /MANIFESTUAC:"level='asInvoker' uiAccess='false'"
rem SET MANIFEST_OPTIONS=/MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed

SET VCVARSBAT="C:\Program Files (x86)/Microsoft Visual Studio 11.0/VC/WPSDK/WP80/vcvarsphoneall.bat"

echo "-------- Windows Phone 8.0"

SET TOOLCHAIN=x86
SET SUBDIR=v110\wp80\x86
SET MACHINE=X86
SET CRT_OPTION=/MD
SET EXTRA_CL_OPTIONS=/D SQLITE_OS_WINRT /D WINAPI_FAMILY=WINAPI_FAMILY_PHONE_APP 
SET EXTRA_LINK_OPTIONS=
SET LIBS=WindowsPhoneCore.lib RuntimeObject.lib PhoneAppModelHost.lib 
cmd /c b.bat

SET TOOLCHAIN=x86_arm
SET SUBDIR=v110\wp80\arm
SET MACHINE=ARM
SET CRT_OPTION=/MD
SET EXTRA_CL_OPTIONS=/D _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE=1 /D SQLITE_OS_WINRT /D WINAPI_FAMILY=WINAPI_FAMILY_PHONE_APP 
SET EXTRA_LINK_OPTIONS=
SET LIBS=WindowsPhoneCore.lib RuntimeObject.lib PhoneAppModelHost.lib 
cmd /c b.bat

SET LIBS=

SET MANIFEST_OPTIONS=/MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed

SET VCVARSBAT="C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\vcvarsall.bat"

echo "-------- Win XP"

SET TOOLCHAIN=x86
SET SUBDIR=v110\xp\x86
SET MACHINE=X86
SET CRT_OPTION=/MT
SET EXTRA_CL_OPTIONS=/D _USING_V110_SDK71_
SET EXTRA_LINK_OPTIONS=
cmd /c b.bat

SET TOOLCHAIN=x86_amd64
SET SUBDIR=v110\xp\x64
SET MACHINE=X64
SET CRT_OPTION=/MT
SET EXTRA_CL_OPTIONS=/D _USING_V110_SDK71_
SET EXTRA_LINK_OPTIONS=
cmd /c b.bat

SET TOOLCHAIN=x86_arm
SET SUBDIR=v110\xp\arm
SET MACHINE=ARM
SET CRT_OPTION=/MT
SET EXTRA_CL_OPTIONS=/D _USING_V110_SDK71_ /D _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE=1
SET EXTRA_LINK_OPTIONS=
cmd /c b.bat

echo "-------- v110 plain, did not build before"

SET TOOLCHAIN=x86
SET SUBDIR=v110\plain\x86
SET MACHINE=X86
SET CRT_OPTION=/MT
SET EXTRA_CL_OPTIONS=
SET EXTRA_LINK_OPTIONS=
cmd /c b.bat

SET TOOLCHAIN=x86_amd64
SET SUBDIR=v110\plain\x64
SET MACHINE=X64
SET CRT_OPTION=/MT
SET EXTRA_CL_OPTIONS=
SET EXTRA_LINK_OPTIONS=
cmd /c b.bat

SET TOOLCHAIN=x86_arm
SET SUBDIR=v110\plain\arm
SET MACHINE=ARM
SET CRT_OPTION=/MT
SET EXTRA_CL_OPTIONS=/D _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE=1
SET EXTRA_LINK_OPTIONS=
cmd /c b.bat

echo "-------- v110 appcontainer, for Win 8.0 store app"

SET TOOLCHAIN=x86
SET SUBDIR=v110\appcontainer\x86
SET MACHINE=X86
SET CRT_OPTION=/MT
SET EXTRA_CL_OPTIONS=
SET EXTRA_LINK_OPTIONS=/APPCONTAINER
cmd /c b.bat

SET TOOLCHAIN=x86_amd64
SET SUBDIR=v110\appcontainer\x64
SET MACHINE=X64
SET CRT_OPTION=/MT
SET EXTRA_CL_OPTIONS=
SET EXTRA_LINK_OPTIONS=/APPCONTAINER
cmd /c b.bat

SET TOOLCHAIN=x86_arm
SET SUBDIR=v110\appcontainer\arm
SET MACHINE=ARM
SET CRT_OPTION=/MT
SET EXTRA_CL_OPTIONS=/D _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE=1
SET EXTRA_LINK_OPTIONS=/APPCONTAINER
cmd /c b.bat

SET VCVARSBAT="C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat"

echo "-------- v120 appcontainer, for Win 8.1 store app"

SET TOOLCHAIN=x86
SET SUBDIR=v120\appcontainer\x86
SET MACHINE=X86
SET CRT_OPTION=/MD
SET EXTRA_CL_OPTIONS=
SET EXTRA_LINK_OPTIONS=/APPCONTAINER
cmd /c b.bat

SET TOOLCHAIN=x86_amd64
SET SUBDIR=v120\appcontainer\x64
SET MACHINE=X64
SET CRT_OPTION=/MD
SET EXTRA_CL_OPTIONS=
SET EXTRA_LINK_OPTIONS=/APPCONTAINER
cmd /c b.bat

SET TOOLCHAIN=x86_arm
SET SUBDIR=v120\appcontainer\arm
SET MACHINE=ARM
SET CRT_OPTION=/MD
SET EXTRA_CL_OPTIONS=/D _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE=1
SET EXTRA_LINK_OPTIONS=/APPCONTAINER
cmd /c b.bat

echo "-------- Windows Phone 8.1"

SET TOOLCHAIN=x86
SET SUBDIR=v120\wp81\x86
SET MACHINE=X86
SET CRT_OPTION=/MD
SET EXTRA_CL_OPTIONS=/D SQLITE_OS_WINRT /D WINAPI_FAMILY=WINAPI_FAMILY_PHONE_APP 
SET EXTRA_LINK_OPTIONS=/APPCONTAINER
cmd /c b.bat

SET TOOLCHAIN=x86_arm
SET SUBDIR=v120\wp81\arm
SET MACHINE=ARM
SET CRT_OPTION=/MD
SET EXTRA_CL_OPTIONS=/D _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE=1 /D SQLITE_OS_WINRT /D WINAPI_FAMILY=WINAPI_FAMILY_PHONE_APP 
SET EXTRA_LINK_OPTIONS=/APPCONTAINER
cmd /c b.bat

SET VCVARSBAT="C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"

echo "-------- v140 plain, not built before"

SET TOOLCHAIN=x86
SET SUBDIR=v140\plain\x86
SET MACHINE=X86
SET CRT_OPTION=/MT
SET EXTRA_CL_OPTIONS=
SET EXTRA_LINK_OPTIONS=
cmd /c b.bat

SET TOOLCHAIN=x86_amd64
SET SUBDIR=v140\plain\x64
SET MACHINE=X64
SET CRT_OPTION=/MT
SET EXTRA_CL_OPTIONS=
SET EXTRA_LINK_OPTIONS=
cmd /c b.bat

SET TOOLCHAIN=x86_arm
SET SUBDIR=v140\plain\arm
SET MACHINE=ARM
SET CRT_OPTION=/MT
SET EXTRA_CL_OPTIONS=/D _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE=1
SET EXTRA_LINK_OPTIONS=
cmd /c b.bat

echo "-------- v140 appcontainer, for uwp"

SET TOOLCHAIN=x86
SET SUBDIR=v140\appcontainer\x86
SET MACHINE=X86
SET CRT_OPTION=/MT
SET EXTRA_CL_OPTIONS=
SET EXTRA_LINK_OPTIONS=/APPCONTAINER
cmd /c b.bat

SET TOOLCHAIN=x86_amd64
SET SUBDIR=v140\appcontainer\x64
SET MACHINE=X64
SET CRT_OPTION=/MT
SET EXTRA_CL_OPTIONS=
SET EXTRA_LINK_OPTIONS=/APPCONTAINER
cmd /c b.bat

SET TOOLCHAIN=x86_arm
SET SUBDIR=v140\appcontainer\arm
SET MACHINE=ARM
SET CRT_OPTION=/MT
SET EXTRA_CL_OPTIONS=/D _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE=1
SET EXTRA_LINK_OPTIONS=/APPCONTAINER
cmd /c b.bat


