LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE    := libe_sqlite3
LOCAL_MODULE_FILENAME    := libe_sqlite3
LOCAL_CFLAGS := -O -DNDEBUG -DSQLITE_TEMP_STORE=3 -DSQLITE_DEFAULT_FOREIGN_KEYS=1 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_RTREE
LOCAL_SRC_FILES = ../../../sqlite3/sqlite3.c

include $(BUILD_SHARED_LIBRARY)

